import { useCallback, useEffect, useRef, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router';
import type { Session } from '@supabase/supabase-js';
import { ArrowLeft, ArrowUpRight, BookOpen, CalendarClock, Check, Clock3, Gift, Headphones, History, LayoutDashboard, LoaderCircle, LogOut, Mail, NotebookPen, Pause, Phone, Plus, RefreshCw, Settings2, ShieldCheck, Sparkles } from 'lucide-react';
import Brand from '@/components/Brand';
import MemberControls from '@/components/MemberControls';
import AccountSignIn from '@/components/AccountSignIn';
import PhoneSignInSettings from '@/components/PhoneSignInSettings';
import DashboardPreferences from '@/components/DashboardPreferences';
import SavedNotes from '@/components/SavedNotes';
import { useDraft } from '@/lib/draft';
import { continuationDraft } from '@/lib/continuity';
import { supabase } from '@/lib/supabase';
import { getPortalMember, portalRequest, type PortalMember } from '@/lib/portal';
import { CONTENT_TYPES, planLabel, schedulingRequest, VOICES, type CallPlan } from '@/lib/scheduled-calls';
import { deliveryLabels, formatMoment, nextPlan, planState, type Capabilities, type DashboardData } from '@/lib/dashboard';
import { PHONE_DISPLAY, PHONE_TEL } from '@/lib/phone';
import '@/dashboard.css';

const tabs=[{id:'overview',name:'Overview',icon:LayoutDashboard},{id:'schedules',name:'Scheduled calls',icon:CalendarClock},{id:'notes',name:'Saved notes',icon:NotebookPen},{id:'history',name:'Call history',icon:History},{id:'settings',name:'Preferences',icon:Settings2}];
const modeNames:Record<string,string>={journey:'The Journey',sermon:'The Pulpit Walk',inspiration:'Daily Check-In',random:'Surprise Me'};
const contentName=(id:string)=>CONTENT_TYPES.find(type=>type.id===id)?.name||'Scripture call';

export default function MemberRoom(){
 const navigate=useNavigate();const {setPrivateDraft}=useDraft();
 const location=useLocation();const requested=new URLSearchParams(location.search).get('view');
 const view=location.hash==='#calling-preferences'?'settings':tabs.some(tab=>tab.id===requested)?requested!:'overview';
 const [session,setSession]=useState<Session|null>(null);const [authLoading,setAuthLoading]=useState(true);
 const [member,setMember]=useState<PortalMember|null>(null);const [data,setData]=useState<DashboardData|null>(null);
 const [caps,setCaps]=useState<Capabilities|null>(null);const [loading,setLoading]=useState(true);
 const [memberError,setMemberError]=useState('');const [dataError,setDataError]=useState('');const [notice,setNotice]=useState('');const [actionError,setActionError]=useState('');
 const [busy,setBusy]=useState('');const sequence=useRef(0);const accountId=useRef<string|null>(null);
 function continueHistory(entry:HistoryEntry){if(!session)return;setPrivateDraft(continuationDraft({title:entry.title.slice(0,80),body:entry.summary.slice(0,1200)}),session.user.id);navigate('/begin/');}
 useEffect(()=>{
  let active=true;let authEvent=false;
  const generation=sequence;
  void supabase.auth.getSession().then(({data})=>{if(active&&!authEvent){accountId.current=data.session?.user.id||null;setSession(data.session);setAuthLoading(false);}}).catch(()=>{if(active&&!authEvent){setAuthLoading(false);setActionError('Your session could not be restored. Please sign in again.');}});
  const {data:listener}=supabase.auth.onAuthStateChange((_event,next)=>{if(active){authEvent=true;accountId.current=next?.user.id||null;sequence.current++;setSession(next);setAuthLoading(false);setMember(null);setData(null);setNotice('');setActionError('');setBusy('');}});
  return()=>{active=false;generation.current++;listener.subscription.unsubscribe();};
 },[]);
 const refresh=useCallback(()=>{
  if(!session||accountId.current!==session.user.id)return Promise.resolve();
  const current=++sequence.current;
  return Promise.allSettled([getPortalMember(session),schedulingRequest<DashboardData>('/dashboard',session),schedulingRequest<Capabilities>('/capabilities')]).then(results=>{
  if(current!==sequence.current||accountId.current!==session.user.id)return;
  const [account,dashboard,capabilities]=results;
  if(account.status==='fulfilled'){setMember(account.value);setMemberError('');}else setMemberError('Your calling details could not be refreshed.');
  if(dashboard.status==='fulfilled'){setData(dashboard.value);setDataError('');}else setDataError('Your schedules and preferences could not be refreshed.');
  setCaps(capabilities.status==='fulfilled'?capabilities.value:null);setLoading(false);
  });
 },[session]);
 useEffect(()=>{const generation=sequence;void refresh();return()=>{generation.current++;};},[refresh]);
 async function signOut(){setBusy('signout');setActionError('');try{const {error}=await supabase.auth.signOut();if(error)throw error;}catch{setActionError('Sign out did not complete. Please try again.');}finally{setBusy('');}}
 async function pausePlan(plan:CallPlan){
  if(busy)return;setBusy(plan.id);setActionError('');setNotice('');
  try{await schedulingRequest(`/plans/${plan.id}/pause`,session,{});setNotice(`${contentName(plan.content_type)} is paused. A call already ringing may still arrive.`);await refresh();}
  catch{setActionError('We could not confirm the pause. Refresh your dashboard before trying again.');}finally{setBusy('');}
 }
 async function pauseLegacy(mode:string){
  if(!session||busy)return;setBusy(mode);setActionError('');
  try{const {status}=await portalRequest('/cancel',session,{mode});if(status!==200)throw Error();setNotice(`${modeNames[mode]||'Your journey'} is paused.`);await refresh();}
  catch{setActionError('We could not confirm the pause. Refresh and check your journey.');}finally{setBusy('');}
 }
 if(authLoading)return <div className="elroi-site dash-auth-loading" role="status"><LoaderCircle className="animate-spin" size={26}/><p>Opening your dashboard…</p></div>;
 if(!session)return <DashboardSignIn initialError={actionError}/>;
 const plans=data?.plans||[];const next=nextPlan(plans);const activePlans=plans.filter(plan=>planState(plan)==='Scheduled');
 const legacy=(member?.schedules||[]).filter(track=>track.active);
 const name=data?.preferences.display_name||member?.caller_name||'';const firstName=name.trim().split(/\s+/)[0];
 const zone=data?.preferences.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone;
 const history=[...(member?.history||[]).map((item,index)=>({id:`call-${item.id||index}`,date:item.created_at||'',title:item.figure_name?`A conversation through ${item.figure_name}`:'Your conversation with El Roi',summary:item.summary||'No summary was saved for this conversation.',status:'On demand',references:[] as string[],kind:'conversation'})),...(data?.history||[]).map(item=>({id:item.id,date:item.due_at,title:item.title||item.topic,summary:`${contentName(item.content_type)} · ${item.voice}`,status:deliveryLabels[item.status]||item.status,references:item.references,kind:'scheduled'}))].sort((a,b)=>Date.parse(b.date)-Date.parse(a.date));
 return <div className="elroi-site dash-layout">
  <a className="elroi-skip" href="#main-content">Skip to dashboard</a>
  <aside className="dash-sidebar"><Brand/><p className="dash-sidebar-label">YOUR SPACE</p><nav aria-label="Dashboard navigation">{tabs.map(tab=><Link key={tab.id} to={`/account/?view=${tab.id}`} aria-current={view===tab.id?'page':undefined}><tab.icon size={19}/>{tab.name}{tab.id==='schedules'&&activePlans.length>0&&<span>{activePlans.length}</span>}</Link>)}</nav><div className="dash-sidebar-bottom"><div className="dash-sidebar-note"><Headphones size={24}/><strong>A little space for you.</strong><p>You can call whenever something is on your heart.</p><a href={PHONE_TEL}>Call El Roi <ArrowUpRight size={15}/></a></div><Link to="/"><ArrowLeft size={16}/>Back to website</Link><button type="button" onClick={()=>void signOut()} disabled={busy==='signout'}><LogOut size={16}/>{busy==='signout'?'Signing out…':'Sign out'}</button></div></aside>
  <div className="dash-workspace"><header className="dash-topbar"><div><span>My dashboard</span><span className="dash-topbar-divider">/</span><strong>{tabs.find(tab=>tab.id===view)?.name}</strong></div><div className="dash-topbar-actions"><button type="button" className="dash-refresh" onClick={()=>{setLoading(true);void refresh();}} disabled={loading} aria-label="Refresh dashboard"><RefreshCw size={18} className={loading?'animate-spin':''}/></button><Link to="/schedule/" className="elroi-button elroi-button-primary"><Plus size={17}/><span>Schedule a call</span></Link><Link to="/account/?view=settings" className="dash-avatar" aria-label="Account preferences">{(firstName||session.user.email||'E').slice(0,1).toUpperCase()}</Link></div></header>
  <main id="main-content" className="dash-main">
   <div className="dash-page-heading"><div><p className="elroi-kicker">{view==='overview'?'A LITTLE SPACE. A DEEPER CONNECTION.':'YOUR EL ROI CALL'}</p><h1>{view==='overview'?(firstName?`Welcome back, ${firstName}.`:'Make yourself at home.'):view==='schedules'?'Your moments, on your time.':view==='history'?'Keep the conversation close.':view==='notes'?'Your words. A place to return.':'Make this space yours.'}</h1><p>{view==='overview'?'Call when you need to. Make time for Scripture when you want to.':view==='schedules'?'Every plan is yours to choose, revisit, or pause.':view==='history'?'Return to your conversations and the Scripture you explored.':view==='notes'?'Choose what to keep, what to share, and what to leave behind.':'Your name, your voice, your rhythm.'}</p></div></div>
   {loading&&!member&&!data&&<div className="dash-loading" role="status"><LoaderCircle size={22} className="animate-spin"/>Loading your private space…</div>}
   {(memberError||dataError)&&<div className="dash-error-box" role="alert"><p>{memberError} {dataError} {member||data?'Some information below may be out of date.':''}</p><button type="button" className="elroi-text-link" disabled={loading} onClick={()=>{setLoading(true);void refresh();}}>Try again <RefreshCw size={15}/></button></div>}
   {notice&&<p className="dash-banner" role="status"><Check size={18}/>{notice}</p>}{actionError&&<p className="dash-error-box" role="alert">{actionError}</p>}
   {caps&&!caps.ready&&<div className="dash-service-note"><Clock3 size={17}/><p>Scheduled calling is being connected. You can explore the planner and save your preferences. No new call will be booked yet.</p></div>}
   {view==='overview'&&<>
    <SavedNotes key={session.user.id} session={session} compact/>
    <section className="dash-welcome-grid"><article className="dash-moment"><div className="dash-moment-orbit" aria-hidden="true"><span/><span/><Headphones/></div><p className="dash-light-kicker">{next?'YOUR NEXT SCHEDULED CALL':'THE LINE IS OPEN TO YOU'}</p><h2>{next?contentName(next.content_type):'Come as you are.'}</h2><p>{next?next.topic:'A busy morning. A big question. Something you haven’t found the words for yet.'}</p>{next&&<div className="dash-next-time"><CalendarClock size={18}/><span>{formatMoment(next.next_run_at!,next.timezone)}<small>{next.timezone.replaceAll('_',' ')} · {next.voice} · about {next.duration_minutes} min</small></span></div>}<div className="dash-moment-actions"><a href={PHONE_TEL} className="elroi-button elroi-button-white"><Phone size={17}/>Call now</a><Link to={next?'/account/?view=schedules':'/schedule/'}>{next?'Manage my calls':'Choose a calling time'}<ArrowUpRight size={17}/></Link></div><span className="dash-moment-number">{PHONE_DISPLAY} · Your on-demand line</span></article><article className="dash-scripture"><span className="elroi-icon-tile"><BookOpen size={23}/></span><p className="elroi-kicker">A MOMENT IN SCRIPTURE</p><blockquote>“Be still, and know that I am God.”</blockquote><p>Psalm 46:10 · King James Version</p><Link to="/schedule/?topic=Psalm%2046&content=bible_study">Make room for this passage <ArrowUpRight size={16}/></Link></article></section>
    <section className="dash-metrics" aria-label="Your activity"><Metric icon={Phone} value={member?String(member.total_calls||0):'—'} label="On-demand conversations"/><Metric icon={CalendarClock} value={data?String(activePlans.length):'—'} label="Scheduled learning plans"/><Metric icon={BookOpen} value={data?String(data.stats.lessons_finished):'—'} label="Lessons finished"/></section>
    {member&&!member.phone_verified&&<div className="dash-setup"><span className="elroi-icon-tile"><ShieldCheck size={23}/></span><div><h2>Make your account call-ready.</h2><p>Connect and verify your number to bring your call history into this space.</p></div><Link className="elroi-button elroi-button-dark" to="/account/#calling-preferences">Connect my phone <ArrowUpRight size={16}/></Link></div>}
    <section className="dash-card"><SectionHeading kicker="AT YOUR PACE" title="Your upcoming calls" action={<Link to="/account/?view=schedules" className="elroi-text-link">View all <ArrowUpRight size={16}/></Link>}/>{data?activePlans.length?<div className="dash-upcoming-list">{[...activePlans].sort((a,b)=>Date.parse(a.next_run_at!)-Date.parse(b.next_run_at!)).slice(0,3).map(plan=><div key={plan.id}><span className="elroi-icon-tile"><CalendarClock size={22}/></span><div><h3>{contentName(plan.content_type)}</h3><p>{plan.topic}</p></div><div className="dash-upcoming-time"><strong>{formatMoment(plan.next_run_at!,plan.timezone)}</strong><span>{plan.timezone.replaceAll('_',' ')} · {plan.voice}</span></div></div>)}</div>:<EmptyState icon={CalendarClock} title="A little time, just for Scripture." body="Choose what you want to hear, a voice you enjoy, and a time that fits your life." action={<Link to="/schedule/" className="elroi-button elroi-button-primary"><Plus size={17}/>Build my first schedule</Link>}/>:<p className="dash-help">{dataError?'Schedules are unavailable. Use Try again above.':'Loading your schedules…'}</p>}</section>
    <section className="dash-card"><SectionHeading kicker="PICK UP THE THREAD" title="Recent conversations" action={<Link to="/account/?view=history" className="elroi-text-link">View history <ArrowUpRight size={16}/></Link>}/>{history.length?<HistoryList entries={history.slice(0,3)} zone={zone} onContinue={continueHistory}/>:<EmptyState icon={History} title="Your story can keep growing here." body="Once your phone is verified, your saved conversations and scheduled-call activity appear here." action={<a href={PHONE_TEL} className="elroi-text-link">Start a conversation <Phone size={16}/></a>}/>}</section>
   </>}
   {view==='notes'&&<SavedNotes key={session.user.id} session={session}/>}
   {view==='schedules'&&<><section className="dash-card"><SectionHeading kicker="BIBLE LEARNING CALLS" title="Your scheduled calls" action={<Link className="elroi-button elroi-button-primary" to="/schedule/"><Plus size={17}/>New schedule</Link>}/>{data?plans.length?<div className="dash-plan-grid">{plans.map(plan=><article key={plan.id} className="dash-plan"><div className="dash-plan-top"><span className="elroi-icon-tile"><BookOpen size={22}/></span><span className="dash-tag" data-active={planState(plan)==='Scheduled'}>{planState(plan)}</span></div><h3>{contentName(plan.content_type)}</h3><p className="dash-plan-topic">{plan.topic}</p><dl><div><dt>When</dt><dd>{plan.local_time.slice(0,5)} · {planLabel(plan)}</dd></div><div><dt>Time zone</dt><dd>{plan.timezone.replaceAll('_',' ')}</dd></div><div><dt>Voice & length</dt><dd>{VOICES.find(v=>v.id===plan.voice)?.name||plan.voice} · about {plan.duration_minutes} min</dd></div><div><dt>Calling</dt><dd>Number ending in {plan.phone_last4}</dd></div></dl>{plan.next_run_at&&<p className="dash-plan-next"><CalendarClock size={15}/>Next: {formatMoment(plan.next_run_at,plan.timezone)}</p>}{plan.last_status&&<p className="dash-help">Last call: {deliveryLabels[plan.last_status]||plan.last_status}</p>}<div className="dash-plan-actions">{plan.active&&plan.next_run_at?<button type="button" className="elroi-text-link" disabled={Boolean(busy)} onClick={()=>void pausePlan(plan)}><Pause size={16}/>{busy===plan.id?'Pausing…':'Pause calls'}</button>:<Link className="elroi-text-link" to={`/schedule/?from=${plan.id}`}>Schedule again <ArrowUpRight size={16}/></Link>}<Link className="elroi-text-link" to="/account/?view=history">Call history</Link></div></article>)}</div>:<EmptyState icon={CalendarClock} title="Choose a rhythm that feels like you." body="A study before work. A story in the evening. Bible facts over your coffee. You choose." action={<Link to="/schedule/" className="elroi-button elroi-button-primary">Explore the planner <ArrowUpRight size={17}/></Link>}/>:<p className="dash-help">{dataError?'Your schedules could not be loaded.':'Loading schedules…'}</p>}</section>
    {legacy.length>0&&<section className="dash-card"><SectionHeading kicker="YOUR EXISTING JOURNEYS" title="Keep walking through Scripture"/><p className="dash-help">These are your earlier recurring journeys. They continue separately from the new learning plans.</p><div className="dash-legacy-list">{legacy.map(track=><div key={track.mode}><div><h3>{modeNames[track.mode]||track.mode}</h3><p>{String(track.hour_local||0).padStart(2,'0')}:{String(track.minute_local||0).padStart(2,'0')} · {track.days} · {track.tz?.replaceAll('_',' ')}</p>{track.progress?.next&&<p>Next passage: {track.progress.next}</p>}</div><button type="button" disabled={Boolean(busy)} className="elroi-text-link" onClick={()=>void pauseLegacy(track.mode)}><Pause size={15}/>Pause</button></div>)}</div></section>}
   </>}
   {view==='history'&&<section className="dash-card"><SectionHeading kicker="CONVERSATIONS & SCRIPTURE" title="Your call history"/><p className="dash-help">Recent activity, shown in {zone.replaceAll('_',' ')}. A call ending does not always mean the lesson was heard in full.</p>{history.length?<HistoryList entries={history} zone={zone} onContinue={continueHistory}/>:<EmptyState icon={History} title="This is where you can return." body="Your verified phone connects past conversations to your account. Future scheduled calls will show their outcome and Scripture references here." action={<Link to="/account/#calling-preferences" className="elroi-text-link">Check my phone connection <ArrowUpRight size={16}/></Link>}/>}</section>}
   {view==='settings'&&<div className="dash-settings-grid">{data&&<DashboardPreferences key={JSON.stringify(data.preferences)} session={session} initial={data.preferences} voiceReady={caps?.voice_ready===true} onSaved={async()=>{await refresh();setNotice('Your preferences are saved. New schedules will start with these choices.');}}/>}<div className="dash-form-stack"><PhoneSignInSettings key={session.user.id} session={session}/>{member&&<MemberControls key={`${member.phone}-${member.phone_verified}`} session={session} member={member} onRefresh={refresh}/>}<section className="dash-card"><SectionHeading kicker="YOUR ACCOUNT" title="Private by default"/><p className="dash-account-email"><Mail size={17}/>{session.user.email}</p><p className="dash-help">Your preferences and history belong to this account. Scheduled narration is AI generated, and these calls are not recorded.</p><div className="dash-account-links"><Link to="/privacy/">Privacy policy <ArrowUpRight size={14}/></Link><Link to="/terms/">Terms <ArrowUpRight size={14}/></Link></div><button type="button" className="elroi-text-link" disabled={Boolean(busy)} onClick={()=>void signOut()}><LogOut size={16}/>Sign out of this device</button></section></div></div>}
   <footer className="dash-footer"><span><ShieldCheck size={15}/>Your private El Roi space.</span><Link to="/gift/"><Gift size={15}/>Gift a conversation</Link><a href={PHONE_TEL}>{PHONE_DISPLAY}</a></footer>
  </main></div>
 </div>;
}
function Metric({icon:Icon,value,label}:{icon:typeof Phone;value:string;label:string}){return <article className="dash-metric"><span className="elroi-icon-tile"><Icon size={21}/></span><div><strong>{value}</strong><p>{label}</p></div></article>;}
function SectionHeading({kicker,title,action}:{kicker:string;title:string;action?:React.ReactNode}){return <div className="dash-section-heading"><div><p className="elroi-kicker">{kicker}</p><h2>{title}</h2></div>{action}</div>;}
function EmptyState({icon:Icon,title,body,action}:{icon:typeof Phone;title:string;body:string;action?:React.ReactNode}){return <div className="dash-empty"><span className="elroi-icon-tile"><Icon size={23}/></span><h3>{title}</h3><p>{body}</p>{action}</div>;}
type HistoryEntry={id:string;date:string;title:string;summary:string;status:string;references:string[];kind:string};
function HistoryList({entries,zone,onContinue}:{entries:HistoryEntry[];zone:string;onContinue:(entry:HistoryEntry)=>void}){return <div className="dash-history-list">{entries.map(item=><details key={item.id}><summary><span className="elroi-icon-tile">{item.kind==='scheduled'?<BookOpen size={21}/>:<Phone size={21}/>}</span><span className="dash-history-title"><strong>{item.title}</strong><span>{formatMoment(item.date,zone)}</span></span><span className="dash-tag">{item.status}</span><Plus size={17} className="dash-details-plus"/></summary><div className="dash-history-body"><p>{item.summary}</p>{item.summary!=='No summary was saved for this conversation.'&&<button type="button" className="elroi-text-link" onClick={()=>onContinue(item)}>Continue in writing <ArrowUpRight size={16}/></button>}{item.references.length>0&&<div><h3>Scripture references</h3><ul>{item.references.map(reference=><li key={reference}>{reference}</li>)}</ul></div>}</div></details>)}</div>;}
function DashboardSignIn({initialError}:{initialError:string}){
 return <div className="elroi-site dash-login"><header><Brand/><Link to="/" className="elroi-text-link"><ArrowLeft size={16}/>Back to website</Link></header><main id="main-content" className="dash-login-grid"><section className="dash-login-story"><span className="dash-login-symbol"><Sparkles size={31}/></span><p className="elroi-kicker">YOUR EL ROI SPACE</p><h1>A little space.<br/>All your own.</h1><p>Your conversations, your time in Scripture, and the voice that feels right for you. Together in one peaceful place.</p><div className="dash-login-features"><span><CalendarClock size={20}/>Choose when we call</span><span><Headphones size={20}/>Find your preferred voice</span><span><BookOpen size={20}/>Return to what you learned</span></div></section><section className="dash-login-panel"><span className="elroi-icon-tile"><ShieldCheck size={24}/></span><h2>Welcome to your dashboard.</h2><p>Choose how to verify and return to your account. First time here? Start with email.</p><AccountSignIn initialError={initialError}/><div className="dash-login-call"><Phone size={19}/><div><strong>Need a conversation now?</strong><a href={PHONE_TEL}>Call {PHONE_DISPLAY}</a></div></div><p className="dash-login-privacy"><ShieldCheck size={14}/>Your history appears only after phone verification.</p></section></main></div>;
}
