// Scripture-led artwork is independent of seasonal decoration.
// Each reference is a chapter inside that day's actual assignment.
export const READING_SCENES = {
  creation: 'Sunlight over a lush river valley, an illustration of creation',
  hagar: 'An artistic depiction of Hagar beside a spring in the wilderness',
  joseph: 'An artistic depiction of Joseph overseeing grain stores in ancient Egypt',
  tabernacle: 'An artistic reconstruction of the tabernacle in a desert courtyard',
  wilderness: 'A path through the Sinai wilderness with distant tents and travelers',
  'promised-land': 'Olive trees and fertile fields overlooking the Jordan valley',
  ruth: 'An artistic depiction of Ruth gleaning barley in a field near Bethlehem',
  samuel: 'An oil lamp burning inside an ancient sanctuary',
  david: 'An artistic depiction of the young shepherd David with a lyre on a hillside',
  temple: 'An artistic reconstruction of the ancient Jerusalem temple courtyard',
  prophet: 'An ancient prophet overlooking a dry valley from a mountain',
  exile: 'An artistic depiction of broken Jerusalem walls and families leaving the city',
  rebuild: 'An artistic depiction of workers rebuilding the walls of Jerusalem',
  esther: 'An artistic depiction of Esther at the entrance of an ancient Persian palace',
  job: 'A solitary man contemplating immense storm clouds, an illustration inspired by Job',
  wisdom: 'An ancient scroll, reed pen, oil lamp and olive branch on a wooden table',
  vineyard: 'An ancient vineyard and garden with fruit trees and a stone watchtower',
  potter: 'An ancient potter shaping clay on a pottery wheel',
  daniel: 'An artistic depiction of Daniel praying beside an open window in Babylon',
  jonah: 'An ancient sailing boat under clearing storm clouds near a rugged coast',
  bethlehem: 'An artistic depiction of the newborn Jesus in a manger with Mary and Joseph',
  galilee: 'A boat and fishing nets on the Sea of Galilee, with people listening to a teacher',
  'empty-tomb': 'An artistic depiction of an empty rock-cut tomb with linen at dawn',
  church: 'An artistic depiction of early Christians sharing bread in a first-century home',
  letters: 'Papyrus, a reed pen and an oil lamp beside a window overlooking an ancient harbor',
  'new-creation': 'An artistic vision of the river of life and fruit-bearing trees in a renewed city',
  rescue: 'An artistic depiction of Israelites walking through the parted sea',
  worship: 'A wooden lyre beside a glowing oil lamp',
} as const;
export type ReadingScene = keyof typeof READING_SCENES;
export type ReadingArtwork = { day: number; scene: ReadingScene; title: string; reference: string; book: string; chapter: number };

const assignments: [ReadingScene, string, string, number][] = [
  ['creation', 'When everything began', 'Genesis', 1],
  ['hagar', 'The God who sees Hagar', 'Genesis', 16],
  ['joseph', 'Joseph: purpose through hardship', 'Genesis', 41],
  ['joseph', 'Provision in Egypt', 'Genesis', 47],
  ['rescue', 'A path through the sea', 'Exodus', 14],
  ['tabernacle', 'A dwelling among the people', 'Exodus', 40],
  ['tabernacle', 'Learning to worship', 'Leviticus', 9],
  ['tabernacle', 'Atonement and a holy people', 'Leviticus', 16],
  ['wilderness', 'Trust in the wilderness', 'Numbers', 14],
  ['wilderness', 'The long road to the promise', 'Numbers', 33],
  ['promised-land', 'Remember the journey', 'Deuteronomy', 8],
  ['wisdom', 'Words to carry into the land', 'Deuteronomy', 17],
  ['promised-land', 'Crossing into the promise', 'Joshua', 3],
  ['promised-land', 'A land and an inheritance', 'Joshua', 21],
  ['promised-land', 'Choose whom you will serve', 'Joshua', 24],
  ['ruth', 'Faithfulness in an ordinary field', 'Ruth', 2],
  ['samuel', 'Speak, your servant is listening', '1 Samuel', 3],
  ['david', 'A shepherd called to lead', '1 Samuel', 16],
  ['promised-land', 'A kingdom and a lasting promise', '2 Samuel', 7],
  ['wisdom', 'The weight of leadership', '1 Kings', 2],
  ['temple', 'A house of prayer', '1 Kings', 8],
  ['prophet', 'Elijah and the call to return', '1 Kings', 18],
  ['wisdom', 'Rediscovering the book of the law', '2 Kings', 22],
  ['exile', 'Jerusalem falls', '2 Kings', 25],
  ['worship', 'Making room for worship', '1 Chronicles', 25],
  ['temple', 'Dedicating the temple', '2 Chronicles', 7],
  ['temple', 'Renewing the house of God', '2 Chronicles', 24],
  ['exile', 'Exile and an open door home', '2 Chronicles', 36],
  ['rebuild', 'Rebuilding with courage', 'Nehemiah', 6],
  ['esther', 'Courage for such a time', 'Esther', 4],
  ['job', 'Faith when everything is lost', 'Job', 1],
  ['job', 'Honest questions in suffering', 'Job', 19],
  ['job', 'Wonder beyond our understanding', 'Job', 38],
  ['creation', 'The heavens and the work of God', 'Psalms', 8],
  ['david', 'The Lord is my shepherd', 'Psalms', 23],
  ['worship', 'A new song of trust', 'Psalms', 33],
  ['worship', 'A clean heart', 'Psalms', 51],
  ['worship', 'A refuge in every season', 'Psalms', 62],
  ['worship', 'Remembering God’s faithfulness', 'Psalms', 78],
  ['worship', 'Under the shelter of His wings', 'Psalms', 91],
  ['creation', 'Creation sings its praise', 'Psalms', 104],
  ['wisdom', 'A lamp for the path', 'Psalms', 119],
  ['exile', 'Songs far from home', 'Psalms', 137],
  ['worship', 'Let everything praise the Lord', 'Psalms', 150],
  ['wisdom', 'Learning the way of wisdom', 'Proverbs', 3],
  ['wisdom', 'Wisdom in everyday choices', 'Proverbs', 16],
  ['wisdom', 'A time for everything', 'Ecclesiastes', 3],
  ['vineyard', 'Love in the garden', 'Song of Solomon', 4],
  ['wisdom', 'The promise of a coming King', 'Isaiah', 9],
  ['vineyard', 'A vineyard watched over', 'Isaiah', 27],
  ['promised-land', 'The wilderness will rejoice', 'Isaiah', 35],
  ['vineyard', 'Like a well-watered garden', 'Isaiah', 58],
  ['new-creation', 'The promise of a renewed world', 'Isaiah', 65],
  ['potter', 'In the potter’s hands', 'Jeremiah', 18],
  ['wisdom', 'A covenant written on the heart', 'Jeremiah', 31],
  ['exile', 'Grief at the city gates', 'Jeremiah', 39],
  ['exile', 'Mercies in the middle of sorrow', 'Lamentations', 3],
  ['exile', 'Facing the cost of unfaithfulness', 'Ezekiel', 12],
  ['promised-land', 'A land restored, a heart renewed', 'Ezekiel', 36],
  ['temple', 'A vision of restored worship', 'Ezekiel', 40],
  ['daniel', 'Faithfulness in exile', 'Daniel', 6],
  ['vineyard', 'A call to return and flourish', 'Hosea', 14],
  ['jonah', 'Mercy beyond familiar shores', 'Jonah', 1],
  ['wisdom', 'Trust when the fig tree is bare', 'Habakkuk', 3],
  ['temple', 'Rebuild and take heart', 'Haggai', 2],
  ['bethlehem', 'The promised King arrives', 'Matthew', 1],
  ['galilee', 'The kingdom draws near', 'Matthew', 13],
  ['empty-tomb', 'He is risen', 'Matthew', 28],
  ['empty-tomb', 'An empty tomb, a new beginning', 'Mark', 16],
  ['galilee', 'Stories that turn us toward mercy', 'Luke', 15],
  ['empty-tomb', 'Hope on the resurrection morning', 'Luke', 24],
  ['galilee', 'Restored beside the sea', 'John', 21],
  ['church', 'Good news crosses boundaries', 'Acts', 11],
  ['letters', 'The message reaches Rome', 'Acts', 28],
  ['letters', 'Grace and a transformed life', 'Romans', 12],
  ['church', 'One body, many gifts', '1 Corinthians', 12],
  ['letters', 'Strength in weakness', '2 Corinthians', 12],
  ['letters', 'Grace, freedom, and unity', 'Ephesians', 2],
  ['letters', 'Joy and hope that endure', 'Philippians', 4],
  ['letters', 'Faith passed to the next generation', '2 Timothy', 2],
  ['tabernacle', 'A better covenant', 'Hebrews', 9],
  ['church', 'Love made visible', 'James', 2],
  ['letters', 'Truth, love, and faithful witness', '3 John', 1],
  ['new-creation', 'All things made new', 'Revelation', 22],
];

export const READING_ARTWORK: ReadingArtwork[] = assignments.map(([scene, title, book, chapter], index) => ({
  day: index + 1, scene, title, book, chapter, reference: `${book} ${chapter}`,
}));
export function artworkForDay(day: number) {
  return Number.isInteger(day) && day >= 1 && day <= 84 ? READING_ARTWORK[day - 1] : undefined;
}
export function sceneSource(scene: ReadingScene, size: 'small' | 'large' = 'large') {
  return `/images/readings/${scene}${size === 'small' ? '-640' : ''}.webp`;
}
