import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { googleProviderEnabled, googleSignInUrl, GoogleAuthUnavailable, googleAuthError, googleReturnError, rememberGoogleAttempt, GOOGLE_ATTEMPT_KEY } from '../src/lib/google-auth.ts';
const config={supabaseUrl:'https://project.supabase.co',anonKey:'public-test-key'};
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});
const available=async()=>json({external:{google:true}});
function authClient(){const calls=[];return {calls,async signInWithOAuth(request){calls.push(request);const url=new URL(config.supabaseUrl+'/auth/v1/authorize');url.searchParams.set('provider',request.provider);url.searchParams.set('redirect_to',request.options.redirectTo);return {data:{url:url.href},error:null};}};}
function storage(){const values=new Map();return {getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value)};}
test('Google availability comes only from the live provider setting',async()=>{for(const value of [false,undefined,'true',1])assert.equal(await googleProviderEnabled(config,async()=>json({external:{google:value}})),false);assert.equal(await googleProviderEnabled(config,available),true);});
test('availability is a read-only, uncached public settings request',async()=>{await googleProviderEnabled(config,async(url,options)=>{assert.equal(url,config.supabaseUrl+'/auth/v1/settings');assert.equal(options.cache,'no-store');assert.deepEqual(options.headers,{apikey:config.anonKey});assert.equal(options.body,undefined);return json({external:{google:true}});});});
test('disabled Google does not start OAuth or create a session',async()=>{const auth=authClient();await assert.rejects(googleSignInUrl(auth,config,'/account/',async()=>json({external:{google:false}})),GoogleAuthUnavailable);assert.equal(auth.calls.length,0);});
test('a settings outage cannot be reported as enabled',async()=>{const auth=authClient();await assert.rejects(googleSignInUrl(auth,config,'/account/',async()=>json({},503)));assert.equal(auth.calls.length,0);});
test('Google asks only for identity scopes and preserves the scheduling return',async()=>{const auth=authClient();const url=await googleSignInUrl(auth,config,'/schedule/',available);assert.deepEqual(auth.calls[0],{provider:'google',options:{redirectTo:'https://elroicall.com/schedule/',scopes:'openid email profile',queryParams:{prompt:'select_account'},skipBrowserRedirect:true}});assert.equal(new URL(url).searchParams.get('redirect_to'),'https://elroicall.com/schedule/');});
test('dashboard sign-in returns to the canonical dashboard',async()=>{const auth=authClient();await googleSignInUrl(auth,config,'/account/',available);assert.equal(auth.calls[0].options.redirectTo,'https://elroicall.com/account/');});
test('untrusted destinations cannot turn Google sign-in into an open redirect',async()=>{for(const dest of ['https://attacker.invalid','//attacker.invalid','/schedule/?next=evil','http://localhost:3000']){const auth=authClient();await googleSignInUrl(auth,config,dest,available);assert.equal(auth.calls[0].options.redirectTo,'https://elroicall.com/account/');}});
test('SDK errors and missing authorization URLs expose no provider secrets',async()=>{for(const response of [{data:{url:null},error:{message:'private-provider-debug'}},{data:{url:null},error:null}]){await assert.rejects(googleSignInUrl({signInWithOAuth:async()=>response},config,'/account/',available),error=>error.message===googleAuthError());}});
test('only the configured projects Google authorize URL is navigable',async()=>{for(const url of ['https://attacker.invalid/auth/v1/authorize?provider=google','javascript:alert(1)','https://project.supabase.co.evil.invalid/auth/v1/authorize?provider=google','https://project.supabase.co/auth/v1/verify?provider=google','https://project.supabase.co/auth/v1/authorize?provider=github','https://project.supabase.co/auth/v1/authorize?provider=google&redirect_to=https://attacker.invalid']){await assert.rejects(googleSignInUrl({signInWithOAuth:async()=>({data:{url},error:null})},config,'/account/',available));}});
test('Google attempt metadata contains no credentials or personal data',()=>{const s=storage();rememberGoogleAttempt(s,1000);assert.equal(s.getItem(GOOGLE_ATTEMPT_KEY),'1000');});
test('Google cancellation is actionable and never echoes error descriptions',()=>{const s=storage();rememberGoogleAttempt(s,1000);const text=googleReturnError('https://elroicall.com/account/#error=access_denied&error_description=private-provider-debug',s,2000);assert.match(text,/Google sign-in was canceled/);assert.ok(!text.includes('private-provider-debug'));});
test('query callback errors are handled like fragment callback errors',()=>{const s=storage();rememberGoogleAttempt(s,1000);assert.match(googleReturnError('https://elroicall.com/schedule/?error=access_denied',s,2000),/Google/);});
test('stale Google metadata does not mislabel an email link failure',()=>{const s=storage();rememberGoogleAttempt(s,1000);assert.equal(googleReturnError('https://elroicall.com/account/#error=expired',s,601001),'');assert.equal(googleReturnError('https://elroicall.com/account/',s,2000),'');});
test('blocked session storage never breaks sign-in',()=>{const s={setItem(){throw Error('blocked');},getItem(){throw Error('blocked');}};assert.doesNotThrow(()=>rememberGoogleAttempt(s));assert.equal(googleReturnError('https://elroicall.com/account/#error=access_denied',s),'');});
test('the shared sign-in form exposes Google independently of email form validation',async()=>{const source=await readFile(new URL('../src/components/AccountSignIn.tsx',import.meta.url),'utf8');assert.match(source,/type="button" className="auth-google-button"/);assert.match(source,/Continue with Google/);assert.match(source,/googleEnabled !== true/);assert.match(source,/googleSignInUrl\(supabase.auth, googleConfig, destination\)/);assert.match(source,/not your Google password/);assert.ok(source.indexOf('className="auth-google"')<source.indexOf('<Form className="auth-form"'));});
